branches:
  except: release-notes
language: node_js
sudo: false
node_js:
  - 14
cache:
  directories:
    - node_modules
before_install:
  - bash .travis-pre.sh
env:
  global:
    - secure: yIrHdkLhWtO37N24cRU71PK80zvkPzlJ1Jm+1MS3C6/icgJ8At1N/UgpBdxuBs1tlJm1O7Ahk+/MhpGWlspx9tCF7Hzw9Rj0xpKhqsvM155zgH582xNPwNebiCr/tmsH2/ELgFBBgC9sCW5luzeKx9nyuedGA4fmD2fK5Phc5EE=
    - secure: fGRo+RTDcnWNnYjSgDtHIRFrkXDxYzFrF0JaGs73ZunLXoYbJ5FclaM9+wjw8BbGEEsVbyBYMSHyy8E2Y0VRggal/XlFkKaqQQHSDVuslcM5YdAkcLC8jFSuSzP32X6cY+L9fKszFVaO+vn84lXwiQnqgpOHAtN32/eB//5Ky1s=
    - secure: m9ylFoxkeoOjBTYi7IF93Rqq95uJkL95onYJc5k1Xo2wNCDrAfvZ8cv6o70Qr/lpWqvgxPueDP6VXjxKAmSueQnx9uGKyigFCpMH4zl7+7n7l4382Eeyex2uE6kCh/lA4EjkmE3QdIW6l8YCGJD1IoHqVSKPZ67ZSdnapTgGPYQ=
    - secure: Vyedcxqn04Or/NZLOeK+pii6YulrSNQrDHCPmoXQh9IVeefOF4NujL/d7+PQuKiRUED3AOw6Ziib6oDzpFamTXXl5SJ4xeKS6V9NpHXunLUlLCuv37siQ+96WvN8r5IHs0BJV/hVKCFbk7IosEdnK1OAx6KyVpYctNdf4qWa4O4=
script: make test-unit-ci
jobs:
  include:
    - stage: Check
      name: Lint
      script: make lint
    - stage: Check
      name: Types
      script: make test-types

    - stage: Unit Test
      name: Coverage
      addons:
        chrome: stable
      env: BROWSER=ChromeHeadlessCI REPORT_COVERAGE=true
      script: make test-unit-cov-ci
    - name: Chrome
      env: BROWSER=Chrome
      addons:
        chrome: stable
      services:
        - xvfb
    - name: Firefox
      env: BROWSER=Firefox
      addons:
        firefox: latest
      services:
        - xvfb
    - name: Safari
      env: BROWSER=BrowserStackSafari
    - name: Edge
      env: BROWSER=BrowserStackEdge
    - name: Internet Explorer 11
      env: BROWSER=BrowserStackIe11
    - name: iOS 14
      env: BROWSER=BrowserStackIos14
    - name: iOS 13
      env: BROWSER=BrowserStackIos13
    - name: Android 11
      env: BROWSER=BrowserStackAndroid11
    - name: Android 10
      env: BROWSER=BrowserStackAndroid10
    - name: Android 9
      env: BROWSER=BrowserStackAndroid9
    - name: Electron
      env: BROWSER=Electron
      addons:
        chrome: stable
      services:
        - xvfb
    - name: react-recurly
      if: type != pull_request
      env: RECURLY_JS_SHA=$TRAVIS_COMMIT
      script:
        - mkdir -p vendor && cd vendor
        - git clone https://github.com/recurly/react-recurly.git && cd react-recurly
        - make test

    - &e2e
      stage: End-to-End Test
      name: Chrome
      env: BROWSER=BrowserStackChrome
      script: make test-e2e-ci
    - <<: *e2e
      name: Firefox
      env: BROWSER=BrowserStackFirefox
    - <<: *e2e
      name: Safari
      env: BROWSER=BrowserStackSafari
    - <<: *e2e
      name: Edge
      env: BROWSER=BrowserStackEdge
    - <<: *e2e
      name: Internet Explorer 11
      env: BROWSER=BrowserStackIe11
    - <<: *e2e
      name: iOS 14
      env: BROWSER=BrowserStackIos14
    - <<: *e2e
      name: iOS 13
      env: BROWSER=BrowserStackIos13
    - <<: *e2e
      name: Android 11
      env: BROWSER=BrowserStackAndroid11
    - <<: *e2e
      name: Android 10
      env: BROWSER=BrowserStackAndroid10
    - <<: *e2e
      name: Android 9
      env: BROWSER=BrowserStackAndroid9
    - <<: *e2e
      name: Electron
      env: BROWSER=Electron
      addons:
        chrome: stable
      services:
        - xvfb

    - stage: Publish
      name: Publish Artifacts
      addons:
        apt:
          packages:
            - google-cloud-sdk
      script:
        - openssl aes-256-cbc -K $encrypted_7a8336da16e8_key -iv $encrypted_7a8336da16e8_iv -in gcs.json.enc -out gcs.json -d
        - gcloud auth activate-service-account --key-file=gcs.json
        - make build
        - gsutil cp -Z build/* $GCS_BUCKET_URL/$TRAVIS_COMMIT/
