name: DefinitelyTyped
on:
  release:
    types:
      - published

jobs:
  DefinitelyTyped:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Recurly-js
        uses: actions/checkout@v2
        with:
          path: recurly-js
      - name: Checkout DefinitelyTyped
        uses: actions/checkout@v2
        with:
          repository: dbrudner/DefinitelyTyped
          ref: master
          path: DefinitelyTyped
          fetch-depth: 1
      - name: Set remote
        run: |
          cd DefinitelyTyped
          git config user.password ${{ secrets.DEFINITELY_TYPED_PR_GITHUB_ACCESS_TOKEN }}
          git remote set-url origin https://github.com/dbrudner/DefinitelyTyped
          git fetch --unshallow -p origin
          git remote add upstream https://github.com/DefinitelyTyped/DefinitelyTyped.git
          git pull upstream master
      - name: Add DefinitelyTyped header
        run: |
          version=$(cat recurly-js/package.json | jq '.version' -r | sed -ne 's/^\([0-9]*\.[0-9]*\).*/\1/p')
          echo "// Type definitions for non-npm package @recurly/recurly-js $version
          // Project: https://github.com/recurly/recurly-js
          // Definitions by: Dave Brudner <https://github.com/dbrudner>
          //                 Chris Rogers <https://github.com/chrissrogers>
          // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
          // TypeScript Version: 3.1
          $(cat recurly-js/types/index.d.ts)" > recurly-js/types/index.d.ts
      - name: Move files
        run: |
          rm recurly-js/test/types/tsconfig.json recurly-js/test/types/index.d.ts recurly-js/types/tsconfig.json recurly-js/types/tslint.json
          cp -R recurly-js/types/* DefinitelyTyped/types/recurly__recurly-js
          cp -R recurly-js/test/types/* DefinitelyTyped/types/recurly__recurly-js/test
      - id: get-version
        run: |
          version=$(cat recurly-js/package.json | jq '.version' -r )
          echo ::set-output name=version::$version
      - name: open PR
        uses: dbrudner/create-pull-request@v2
        with:
          path: DefinitelyTyped
          commit-message: Updates recurly-js types
          branch: update-recurly-js
          request-to-parent: true
          token: ${{ secrets.DEFINITELY_TYPED_PR_GITHUB_ACCESS_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: Updates types for Recurly.js v${{ steps.get-version.outputs.version }}
          body: |
            # Updates types for Recurly.js v${{ steps.get-version.outputs.version }}

            View the full recurly-js release [here](https://github.com/recurly/recurly-js/releases/tag/v${{ steps.get-version.outputs.version }})

            Note: This is an automated pull request. For more info, see the [Recurly.js](https://github.com/recurly/recurly-js) repository or [documentation](https://developers.recurly.com/reference/recurly-js/index.html).
